---
apiVersion: v1
kind: Namespace
metadata:
  name: nats
  labels:
    name: nats
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: nats
data:
  nats.conf: |
    listen: 0.0.0.0:4222
    http: 0.0.0.0:8222

    authorization {
      user:     nats_client_user
      password: nats_client_pwd
      timeout:  1
    }

    cluster {
      listen: 0.0.0.0:6222

      authorization {
        user: nats_route_user
        password: nats_route_pwd
        timeout: 0.5
      }

      routes = [
        nats://nats_route_user:nats_route_pwd@nats:6222
      ]
    }

    debug: false
    trace: true
    logtime: true
    max_connections: 100
    max_control_line: 512
    max_payload: 65536
    write_deadline: "2s"
---
apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: nats
  labels:
    component: nats
spec:
  selector:
    component: nats
  clusterIP: None
  ports:
  - name: client
    port: 4222
  - name: cluster
    port: 6222
  - name: monitoring
    port: 8222
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: nats
  namespace: nats
  labels:
    component: nats
spec:
  serviceName: nats
  replicas: 3
  template:
    metadata:
      labels:
        component: nats
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: component
                operator: In
                values:
                - nats
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nats
        image: nats:1.4.1
        args: ["--config", "/etc/nats/config/nats.conf"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nats/config
        ports:
        - name: client
          containerPort: 4222
        - name: cluster
          containerPort: 6222
        - name: monitoring
          containerPort: 8222
        livenessProbe:
          httpGet:
            path: /
            port: 8222
          initialDelaySeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: nats-config
          
